
Marcella = [
    'Intl & Development Economics',
    'Development Economics'
    'Art History Arts Management',
    'Arts Management',
    'Computer Science Bridge',
    'Environmental Science',
    'Economics',
    'Chemistry',
    'Energy Systems Management',
    'Energy Systems',
    'Environmental Management',
    'International Studies',
    'Professional Communication',
    'Counseling Psychology',
    'Asia Pacific Graduate Studies',
    'Asia Pacific Studies',
    'APS',
    'Biotechnology',
    'Computer Science',
    'Public Affairs',
    'Psychology',
    'Sports Management',
    'Urban and Public Affairs',
    'Theology & Religious Studies',
    'Computer Science'
]

Cynthia = [
    'Data Science',
    'IME-Intl and Multicultural Educ.',
    'International and Multicultural Education',
    'Nursing',
    'Business Administration',
    'MBA',
    'Nonprofit Administration',
    'Health Informatics',
    'Behavorial Health',
    'Entrepreneurship Innovation',
    'Financial Analysis',
    'Analytics',
    'Education',
    'Learning and Instruction',
    'Public Health',
    'Organization and Leadership',
    'Catholic Educational Leadership',
    'Teach English Speakers Other Lang',
    'Teach English Speakers',
    'TESOL',
    'Healthcare Sys.Ldrship(MSN/RN)',
    'Healthcare'
]


Nina = [
    'Accounting',
    'Business Administration',
    'Entrepreneurship',
    'Innovation',
    'BENI',
    'Management',
    'International Business',
    'Business',
    'Marketing',
    'Finance',
    'Hospitality Management',
    'Undeclared business'
]

Nathan = [
    'Computer Science',
    'Communication Studies',
    'Chemistry',
    'Politics',
    'History',
    'Biology',
    'International Studies',
    'Undeclared Arts',
    'Undeclared Sciences',
    'Advertising',
    'Law',
    'Psychology',
    'Economics',
    'Architecture & Community Design',
    'Architecture',
    'Data Science',
    'Environmental Science',
    'Environmental Studies',
    'English',
    'Comparative Literature & Culture',
    'Comparative Literature',
    'Intl Transaction & Comparative Law',
    'International transaction comparative law'
    'Intellectual Property Tech Law',
    'Mathematics',
    'Media Studies',
    'Fine Arts',
    'Performance Arts & Social Justice',
    'Philosophy',
    'Physics',
    'Sociology',
    'Design',
    'Kinesiology',
    'Japanese Studies',
    'Asian Studies',
    'Urban Studies',
    'Writing'
]


